language: php

php:
  - 7.1
  - 7.2

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_success:
  - travis_retry php ./vendor/bin/coveralls